# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script:
    sh Deploy/build.sh
- task: SSH@0
  inputs:
    sshEndpoint: TencentServer
    commands: sh /home/saturn/script/pr.sh



#Second Choice

#trigger:
#  - master
#
#pool:
#  vmImage: 'ubuntu-latest'
#
#steps:
#  - task: Maven@3
#    inputs:
#      mavenPomFile: 'pom.xml'
#      mavenOptions: '-Xmx3072m'
#      javaHomeOption: 'JDKVersion'
#      jdkVersionOption: '1.8'
#      jdkArchitectureOption: 'x64'
#      publishJUnitResults: true
#      testResultsFiles: '**/surefire-reports/TEST-*.xml'
#      goals: 'package'
#  - task: CopyFilesOverSSH@0
#    inputs:
#      sshEndpoint: TencentServer
#      contents: target/linkage-0.0.1-SNAPSHOT.jar
#      targetFolder: /home/saturn/script/
#  - task: SSH@0
#    inputs:
#      sshEndpoint: TencentServer
#      commands: sh /home/saturn/script/pr.sh
